web:
  build: .
  dockerfile: Dockerfile
  links: ["db", "beanstalkd"]
  ports: 
   - "82:80"
  volumes:
   - .:/var/www/html
  environment:
   APACHE_LOG_DIR: "/var/www/html/logs"
   XDEBUG_CONFIG: "remote_host=192.168.1.210"
db:
  image: orchardup/mysql
  ports:
   - "3306:3306"
  volumes:
   - /var/lib/mysql
  environment:
   - MYSQL_DATABASE=bookmarker
   - MYSQL_USER=homeuser
   - MYSQL_PASSWORD=homeuser
   - character-set-server=utf8
   - collation-server=utf8_general_ci
beanstalkd:
   image: bevand10/alpine-beanstalk
   ports:
    - "11300:11300"
   volumes:
    - ./beanstalkd:/binlog
supervisord:
    image: baffledbear/supervisord
    links: ["beanstalkd", "db"]
beanstalkd_gui:
    image: agaveapi/beanstalkd-console
    ports:
    - "8081:80"
    environment:
      - "BEANSTALKD_HOST=beanstalkd"
      - "BEANSTALKD_PORT=11300"
      - "APACHE_PORT=81"
    links: ["beanstalkd"]
swagger-ui:
  image: swaggerapi/swagger-ui
  ports:
   - "8080:8080"

