book_list:
  path: /book
  defaults: { _controller: 'Bookmarker\Resources\Book::listBooks' }
  methods: ['GET']
  requirements:
    _format: json

book_get:
  path: /book/{id}
  defaults: { _controller: 'Bookmarker\Resources\Book::get' }
  methods: ['GET']
  requirements:
    id: '\d+'
    _format: json

book_post:
  path: /book
  defaults: { _controller: 'Bookmarker\Resources\Book::add' }
  methods: ['POST']

book_put:
  path: /book/{id}
  defaults: { _controller: 'Bookmarker\Resources\Book::replace' }
  methods: ['PUT', 'PATCH']
  requirements:
    id: '\d+'

book_delete:
  path: /book/{id}
  defaults: { _controller: 'Bookmarker\Resources\Book::remove' }
  methods: ['DELETE']
  requirements:
    id: '\d+'

book_download:
  path: /book/{file}.{ext}
  defaults: { _controller: 'Bookmarker\Resources\Book::download' }
  methods: ['GET']
  requirements:
    file: '\w+'
    ext: 'pdf|txt'

book_covers_list:
  path: /book/{id}/covers
  defaults: { _controller: 'Bookmarker\Resources\Book::listBookCovers' }
  methods: ['GET']
  requirements:
    _format: json

book_covers_post:
  path: /book/{id}/covers
  defaults: { _controller: 'Bookmarker\Resources\Book::addCover' }
  methods: ['POST']

book_covers_put:
  path: /book/{id}/covers/{cover_id}
  defaults: { _controller: 'Bookmarker\Resources\Book::replaceCover' }
  methods: ['PUT', 'PATCH']
  requirements:
    id: '\d+'
    cover_id: '\d+'

book_covers_delete:
  path: /book/{id}/covers/{cover_id}
  defaults: { _controller: 'Bookmarker\Resources\Book::removeCover' }
  methods: ['DELETE']
  requirements:
    id: '\d+'
    cover_id: '\d+'

book_cover_download:
  path: /book/{id}/covers/{file}.{ext}
  defaults: { _controller: 'Bookmarker\Resources\Book::downloadCover' }
  methods: ['GET']
  requirements:
    id: '\d+'
    file: '\w+'
    ext: 'png|jpe?g'

book_vote_get:
  path: /book/{id}/votes
  defaults: { _controller: 'Bookmarker\Resources\Book::getRating' }
  methods: ['GET']
  requirements:
    id: '\d+'

book_vote_put:
  path: /book/{id}/votes
  defaults: { _controller: 'Bookmarker\Resources\Book::voteForBook' }
  methods: ['PUT', 'PATCH']
  requirements:
    id: '\d+'

book_vote_delete:
  path: /book/{id}/votes
  defaults: { _controller: 'Bookmarker\Resources\Book::deleteVote' }
  methods: ['DELETE']
  requirements:
    id: '\d+'

book_comments_list:
  path: /book/{id}/comments
  defaults: { _controller: 'Bookmarker\Resources\Book::listComments' }
  methods: ['GET']
  requirements:
    _format: json

book_comment_get:
  path: /book/{id}/comments/{comment_id}
  defaults: { _controller: 'Bookmarker\Resources\Book::getComment' }
  methods: ['GET']
  requirements:
    id: '\d+'
    comment_id: '\d+'

book_comment_put:
  path: /book/{id}/comments/{comment_id}
  defaults: { _controller: 'Bookmarker\Resources\Book::updateComment' }
  methods: ['PUT', 'PATCH']
  requirements:
    id: '\d+'
    comment_id: '\d+'

book_comment_delete:
  path: /book/{id}/comments/{comment_id}
  defaults: { _controller: 'Bookmarker\Resources\Book::deleteComment' }
  methods: ['DELETE']
  requirements:
    id: '\d+'
    comment_id: '\d+'

book_comment_post:
  path: /book/{id}/comments
  defaults: { _controller: 'Bookmarker\Resources\Book::addComment' }
  methods: ['POST']

genre_list:
  path: /genre
  defaults: { _controller: 'Bookmarker\Resources\Genre::listGenres' }
  methods: ['GET']
  requirements:
    _format: json

genre_get:
  path: /genre/{id}
  defaults: { _controller: 'Bookmarker\Resources\Genre::get' }
  methods: ['GET']
  requirements:
    id: '\d+'
    _format: json

genre_post:
  path: /genre
  defaults: { _controller: 'Bookmarker\Resources\Genre::add' }
  methods: ['POST']

genre_put:
  path: /genre/{id}
  defaults: { _controller: 'Bookmarker\Resources\Genre::replace' }
  methods: ['PUT', 'PATCH']
  requirements:
    id: '\d+'

genre_delete:
  path: /genre/{id}
  defaults: { _controller: 'Bookmarker\Resources\Genre::remove' }
  methods: ['DELETE']
  requirements:
    id: '\d+'

author_list:
  path: /author
  defaults: { _controller: 'Bookmarker\Resources\Author::listAuthors' }
  methods: ['GET']
  requirements:
    _format: json

author_get:
  path: /author/{id}
  defaults: { _controller: 'Bookmarker\Resources\Author::get' }
  methods: ['GET']
  requirements:
    id: '\d+'
    _format: json

author_post:
  path: /author
  defaults: { _controller: 'Bookmarker\Resources\Author::add' }
  methods: ['POST']

author_put:
  path: /author/{id}
  defaults: { _controller: 'Bookmarker\Resources\Author::replace' }
  methods: ['PUT', 'PATCH']
  requirements:
    id: '\d+'

author_delete:
  path: /author/{id}
  defaults: { _controller: 'Bookmarker\Resources\Author::remove' }
  methods: ['DELETE']
  requirements:
    id: '\d+'

user_list:
  path: /user
  defaults: { _controller: 'Bookmarker\Resources\User::listUsers' }
  methods: ['GET']
  requirements:
    _format: json

user_get:
  path: /user/{id}
  defaults: { _controller: 'Bookmarker\Resources\User::get' }
  methods: ['GET']
  requirements:
    id: '\d+'
    _format: json

user_post:
  path: /user
  defaults: { _controller: 'Bookmarker\Resources\User::add' }
  methods: ['POST']

user_put:
  path: /user/{id}
  defaults: { _controller: 'Bookmarker\Resources\User::replace' }
  methods: ['PUT', 'PATCH']
  requirements:
    id: '\d+'

user_delete:
  path: /user/{id}
  defaults: { _controller: 'Bookmarker\Resources\User::remove' }
  methods: ['DELETE']
  requirements:
    id: '\d+'

role_list:
  path: /role
  defaults: { _controller: 'Bookmarker\Resources\Role::listRoles' }
  methods: ['GET']
  requirements:
    _format: json

role_get:
  path: /role/{id}
  defaults: { _controller: 'Bookmarker\Resources\Role::get' }
  methods: ['GET']
  requirements:
    id: '\d+'
    _format: json